version: '3.9'

services:
  backend:
    container_name: gs_be_dev
    restart: always
    build:
      context: ../../
      dockerfile: docker/app/Dockerfile
    ports:
      - '${PORT}:${PORT}'
    networks:
      - default
