version: '3.9'

services:
  backend:
    container_name: gs_be_prod
    restart: always
    build:
      context: ../../
      dockerfile: docker/app/Dockerfile
    ports:
      - '${PORT_PROD}:${PORT_PROD}'
    networks:
      - default
