version: "3"

services:
  with-docker-multi-env-production:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: with-docker-multi-env-production
    restart: on-failure
    ports:
      - "3001:3000"
