version: '3.9'

services:
  database:
    image: postgres:14.1
    container_name: gs_db_dev
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - 'POSTGRES_DB=${DB_NAME:-gs_db_dev}'
      - 'POSTGRES_USER=${DB_USERNAME:-postgres}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}'
    volumes:
      - ../../pg_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
    command: '-p ${DB_PORT}'
    extra_hosts:
      - "host.docker.internal:host-gateway"
