version: '3.9'

services:
  postgres-container:
    image: postgres
    container_name: gs_db_stage
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - 'POSTGRES_DB=${DB_NAME:-gs_db_stage}'
      - 'POSTGRES_USER=${DB_USERNAME:-postgres}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}'
    volumes:
      - ../../pg_data_stage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
    command: '-p ${DB_PORT}'
